// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TestServer.Data;

#nullable disable

namespace TestServer.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250913074320_SeedDriversData")]
    partial class SeedDriversData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("TestServer.Models.Driver", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Drivers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Lewis Hamilton"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Max Verstappen"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Charles Leclerc"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Sergio Pérez"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
